[package]
name = "ethereum-tarpc-api"
version = "0.1.0"
authors = ["Artem Vorotnikov <artem@vorotnikov.me>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
primitive-types = { git = "https://github.com/paritytech/parity-common", default-features = false, features = ["serde"] }
serde = { version = "1", features = ["derive"] }
tarpc = "0.23"